Update Repo Branding for .NET Service SDK
iovation/launchkey-dotnet pull request #58
Opened 2020-12-09 20:16 UTC by j7an

2020-12-09 22:27 UTC, jnpblrdrgz approved these changes

2020-12-10 18:45 UTC, CMoncur requested changes

2020-12-10 18:45 UTC, CMoncur commented on README.md
> +The primary entry point to the SDK is a class named `FactoryFactoryBuilder`. This class, located in the `iovation.LaunchKey.Sdk` namespace provides factories for instantiating API clients which can b
Looks like we'll still need to update Iovation to TransUnion in this repo

2020-12-10 18:49 UTC, j7an commented on README.md
> +The primary entry point to the SDK is a class named `FactoryFactoryBuilder`. This class, located in the `iovation.LaunchKey.Sdk` namespace provides factories for instantiating API clients which can b
Correct me if I'm wrong, It looks like thats part of the `iovation.LaunchKey.Sdk` namespace  though.

2020-12-10 21:43 UTC, lordkyzr commented on README.md
> +The primary entry point to the SDK is a class named `FactoryFactoryBuilder`. This class, located in the `iovation.LaunchKey.Sdk` namespace provides factories for instantiating API clients which can b
Yeah that is in the namespace. That is a different ticket we have to resolve that.

2020-12-10 21:48 UTC, lordkyzr approved these changes

2020-12-10 22:56 UTC, CMoncur approved these changes

2020-12-10 23:36 UTC, bporter125 approved these changes

2020-12-15 19:35 UTC, aenglander approved these changes

2020-12-15 19:36 UTC, merged